// SectionRows.test.tsx

// Unit tests for SectionRows component
// Generated by ChatGPT-4, OpenAI

import React from 'react';
import { render, screen, fireEvent } from '@testing-library/react';
import '@testing-library/jest-dom';
import { SectionRows, ISectionRows } from '../SectionRows';
import {IUserData} from "../../../canvas/canvasDataDefs";
import {mockUserData} from "../../../canvas/__mocks__/mockUserData";
import {Course} from "../../../canvas/course/Course";
import {IProfile} from "@canvas/type";

jest.mock('../CourseRow', () => ({
    CourseRow: jest.fn(({ course, onSelectSection }) => <div onClick={() => onSelectSection(course)}>PublishCourseRow: {course.id}</div>),
}));



const mockCourses: Course[] = [
    { id: 1, name: 'Course 1' } as Course,
    { id: 2, name: 'Course 2' } as Course,
];

const mockInstructorsByCourseId = {
    1: [{...mockUserData, id: 1, name: 'Instructor 1' } as IUserData],
    2: [{...mockUserData, id: 2, name: 'Instructor 2' } as IUserData],
};

const mockFrontPageProfilesByCourseId = {
    1: { id: 1, name: 'Profile 1' } as IProfile,
    2: { id: 2, name: 'Profile 2' } as IProfile,
};

const mockPotentialProfilesByCourseId = {
    1: [{ id: 1, name: 'Potential Profile 1' } as IProfile],
    2: [{ id: 2, name: 'Potential Profile 2' } as IProfile],
};

const mockErrorsByCourseId = {
    1: ['Error 1'],
    2: ['Error 2'],
};

const mockSetWorkingSection = jest.fn();
const mockOnOpenAll = jest.fn();
const mockSectionPublishToggle = jest.fn();

const renderComponent = (props: Partial<ISectionRows> = {}) => {
    const defaultProps: ISectionRows = {
        sections: mockCourses,
        instructorsByCourseId: mockInstructorsByCourseId,
        frontPageProfilesByCourseId: mockFrontPageProfilesByCourseId,
        potentialProfilesByCourseId: mockPotentialProfilesByCourseId,
        errorsByCourseId: mockErrorsByCourseId,
        setWorkingSection: mockSetWorkingSection,
        onOpenAll: mockOnOpenAll,
        ...props,
    };

    return render(<SectionRows {...defaultProps} />);
};

describe('SectionRows Component', () => {
    beforeEach(() => {
        jest.clearAllMocks();
    });

    it('renders without crashing', () => {
        renderComponent();
        expect(screen.getByText(/Code/)).toBeInTheDocument();
        expect(screen.getByText(/Name on Front Page/)).toBeInTheDocument();
        expect(screen.getByText(/Instructor\(s\)/)).toBeInTheDocument();
    });

    it('renders the correct number of PublishCourseRow components', () => {
        renderComponent();
        expect(screen.getAllByText(/PublishCourseRow:/)).toHaveLength(mockCourses.length);
    });

    it('calls onOpenAll when "Open All" is clicked', () => {
        renderComponent();
        fireEvent.click(screen.getByText(/Open All/));
        expect(mockOnOpenAll).toHaveBeenCalled();
    });

    it('passes correct props to PublishCourseRow components', () => {
        renderComponent();
        mockCourses.forEach(course => {
            expect(screen.getByText(`PublishCourseRow: ${course.id}`)).toBeInTheDocument();
        });
    });

    it('calls setWorkingSection with the correct course when a PublishCourseRow is clicked', () => {
        renderComponent();
        mockCourses.forEach(course => {
            const courseRow = screen.getByText(`PublishCourseRow: ${course.id}`);
            fireEvent.click(courseRow);
            expect(mockSetWorkingSection).toHaveBeenCalledWith(course);
        });
    });

    describe('Toggle All functionality', () => {
        beforeEach(() => {
            jest.clearAllMocks();
        });

        it('displays "Select All" when most sections are unchecked', () => {
            const mockPublishRecord = {
                1: mockCourses[0], // Only course 1 is checked
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            const toggleLink = screen.getByRole('link', { name: /Select All|Unselect All|Check\/Uncheck All/ });
            expect(toggleLink).toHaveTextContent('Select All');
        });

        it('displays "Unselect All" when most sections are checked', () => {
            const mockPublishRecord = {
                1: mockCourses[0],
                2: mockCourses[1], // Both courses are checked
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            const toggleLink = screen.getByRole('link', { name: /Select All|Unselect All|Check\/Uncheck All/ });
            expect(toggleLink).toHaveTextContent('Unselect All');
        });

        it('displays "Select All" when equal numbers are checked and unchecked', () => {
            const mockPublishRecord = {
                1: mockCourses[0], // 1 checked, 1 unchecked (equal)
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            const toggleLink = screen.getByRole('link', { name: /Select All|Unselect All|Check\/Uncheck All/ });
            expect(toggleLink).toHaveTextContent('Select All');
        });

        it('displays "Check/Uncheck All" when sectionPublishRecord is not provided', () => {
            renderComponent({
                sectionPublishRecord: undefined,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            const toggleLink = screen.getByRole('link', { name: /Select All|Unselect All|Check\/Uncheck All/ });
            expect(toggleLink).toHaveTextContent('Check/Uncheck All');
        });

        it('calls sectionPublishToggle with true for all sections when most are unchecked', () => {
            const mockPublishRecord = {
                1: mockCourses[0], // Only course 1 is checked
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            fireEvent.click(screen.getByText('Select All'));

            expect(mockSectionPublishToggle).toHaveBeenCalledTimes(mockCourses.length);
            mockCourses.forEach(course => {
                expect(mockSectionPublishToggle).toHaveBeenCalledWith(course, true);
            });
        });

        it('calls sectionPublishToggle with false for all sections when most are checked', () => {
            const mockPublishRecord = {
                1: mockCourses[0],
                2: mockCourses[1], // Both courses are checked
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            // Debug: Check what text is actually displayed
            const toggleLink = screen.getByRole('link', { name: /Select All|Unselect All|Check\/Uncheck All/ });
            expect(toggleLink).toHaveTextContent('Unselect All');

            fireEvent.click(toggleLink);

            expect(mockSectionPublishToggle).toHaveBeenCalledTimes(mockCourses.length);
            mockCourses.forEach(course => {
                expect(mockSectionPublishToggle).toHaveBeenCalledWith(course, false);
            });
        });

        it('does not call sectionPublishToggle when sectionPublishToggle is not provided', () => {
            const mockPublishRecord = {
                1: mockCourses[0],
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: undefined,
            });

            // With 1 checked and 1 unchecked, it should show "Select All"
            const toggleLink = screen.getByRole('link', { name: /Select All|Unselect All|Check\/Uncheck All/ });
            expect(toggleLink).toHaveTextContent('Select All');

            fireEvent.click(toggleLink);

            expect(mockSectionPublishToggle).not.toHaveBeenCalled();
        });

        it('does not call sectionPublishToggle when sectionPublishRecord is not provided', () => {
            renderComponent({
                sectionPublishRecord: undefined,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            fireEvent.click(screen.getByText('Check/Uncheck All'));

            expect(mockSectionPublishToggle).not.toHaveBeenCalled();
        });

        it('prevents default form submission when toggle link is clicked', () => {
            const mockPublishRecord = {
                1: mockCourses[0],
            };

            renderComponent({
                sectionPublishRecord: mockPublishRecord,
                sectionPublishToggle: mockSectionPublishToggle,
            });

            const toggleLink = screen.getByText('Select All');
            const mockEvent = { preventDefault: jest.fn() };

            // We need to simulate the event more directly since fireEvent doesn't give us access to the event object
            const clickEvent = new MouseEvent('click', { bubbles: true, cancelable: true });
            Object.defineProperty(clickEvent, 'preventDefault', { value: mockEvent.preventDefault });

            toggleLink.dispatchEvent(clickEvent);

            expect(mockEvent.preventDefault).toHaveBeenCalled();
        });
    });
});
