name: Cleanup PR Artifacts

on:
  pull_request:
    branches:
      - "**"
      - "!main"
    types: [closed]

  workflow_run:
    workflows: [ "Deploying to Test Branch" ]
    types: [ completed ]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete artifacts from workflow runs for this PR
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              event: 'pull_request',
            });

            for (const run of runs.data.workflow_runs) {
              if (run.pull_requests.some(pr => pr.number === prNumber)) {
                console.log(`Deleting artifacts for run ${run.id}...`);
                const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  run_id: run.id,
                });

                for (const artifact of artifacts.data.artifacts) {
                  await github.rest.actions.deleteArtifact({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    artifact_id: artifact.id,
                  });
                  console.log(`Deleted artifact: ${artifact.name}`);
                }
              }
            }
